version: 2.1

jobs:
  vuln-scan:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - run:
          name: install whispers
          command: |
            git clone https://github.com/Skyscanner/whispers
            cd whispers
            make install
      - run:
          name: fetch config
          command: |
            curl -o vuln-config.yaml https://gist.githubusercontent.com/musab/686dda9a2b3d6389d12c837956786eb2/raw/08ad3d30e6c12668dcb6d44baab368376bcc65d1/temp2
      - run:
          name: run whispers
          command: whispers --rules aws-id,aws-secret,apikey,file-contains-password,file-contains-secret vuln-config.yaml

workflows:
  vuln-scan-workflow:
    jobs:
      - vuln-scan
