version: 2.1

jobs:
  vuln-scan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: install whispers
          command: |
            git clone https://github.com/Skyscanner/whispers
            cd whispers
            make install
      - run:
          name: run whispers
          command: whispers --help

workflows:
  vuln-scan-workflow:
    jobs:
      - vuln-scan
